[package]
name = "libsemaphore-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-circom = { git = "https://github.com/gakonst/ark-circom", features=["circom-2"] }
ark-std = { version = "0.3.0", default-features = false, features = ["parallel"] }
ark-bn254 = { version = "0.3.0" }
ark-groth16 = { git = "https://github.com/arkworks-rs/groth16", rev = "765817f", features = ["parallel"] }
num-bigint = { version = "0.4", default-features = false, features = ["rand"] }
ff = { package="ff_ce", version="0.11"}
poseidon-rs = "0.0.8"
color-eyre = "0.5"
sha2 = "0.10.1"
hex = "0.4.0"
once_cell = "1.8"
serde = "1.0"
ethers = "0.6"
hex-literal = "0.3"
proptest = { version = "1.0", optional = true }