name: Build and Test
on: push

env:
  RUST_VERSION: 1.65
  NIGHTLY_VERSION: nightly-2022-11-04

jobs:
  test:
    name: Test
    strategy:
      matrix:
        depth: ["depth_16", "depth_20", "depth_30"]
        dylib: ["dylib", ""]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features lazy_tree,${{ matrix.depth }},${{ matrix.dylib }}